export type { AdminRouterDependencies } from './admin-router';
export { createAdminRouterDependencies } from './admin-router';
export type { AnnouncementRouterDependencies } from './announcement-router';
export { createAnnouncementRouterDependencies } from './announcement-router';
export type { AssignmentRouterDependencies } from './assignment-router';
export { createAssignmentRouterDependencies } from './assignment-router';
export type { CondominiumRouterDependencies } from './condominium-router';
export { createCondominiumRouterDependencies } from './condominium-router';
export type { UserRouterDependencies } from './user-router';
export { createUserRouterDependencies } from './user-router';
