/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PanelRouteImport } from './routes/panel'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PortalIndexRouteImport } from './routes/_portal.index'
import { Route as PanelSpectrumRouteImport } from './routes/panel/spectrum'
import { Route as PanelProviderRouteImport } from './routes/panel.provider'
import { Route as PanelModerationRouteImport } from './routes/panel.moderation'
import { Route as PanelDashboardRouteImport } from './routes/panel.dashboard'
import { Route as PanelAdminRouteImport } from './routes/panel.admin'
import { Route as PanelAccountRouteImport } from './routes/panel.account'
import { Route as DashboardCondoSetupRouteImport } from './routes/dashboard.condo-setup'
import { Route as PanelProviderIndexRouteImport } from './routes/panel.provider.index'
import { Route as PanelModerationIndexRouteImport } from './routes/panel/moderation/index'
import { Route as PanelDashboardIndexRouteImport } from './routes/panel.dashboard.index'
import { Route as PanelProviderConfigurationRouteImport } from './routes/panel/provider/configuration'
import { Route as PanelProviderCondoSetupRouteImport } from './routes/panel.provider.condo-setup'
import { Route as PanelProviderAnnouncementsRouteImport } from './routes/panel/provider/announcements'
import { Route as PanelModerationResidentsRouteImport } from './routes/panel/moderation/residents'
import { Route as PanelModerationReportsRouteImport } from './routes/panel/moderation/reports'
import { Route as PanelModerationCondominiumRouteImport } from './routes/panel/moderation/condominium'
import { Route as PanelModerationAnnouncementsRouteImport } from './routes/panel/moderation/announcements'
import { Route as PanelDashboardConfigurationRouteImport } from './routes/panel/dashboard/configuration'
import { Route as PanelDashboardCondoSetupRouteImport } from './routes/panel.dashboard.condo-setup'
import { Route as PanelDashboardAnnouncementsRouteImport } from './routes/panel/dashboard/announcements'
import { Route as PanelAdminUsersRouteImport } from './routes/panel/admin/users'
import { Route as PanelAdminProvidersRouteImport } from './routes/panel/admin/providers'
import { Route as PanelAdminOverviewRouteImport } from './routes/panel/admin/overview'
import { Route as PanelAdminCondominiumsRouteImport } from './routes/panel/admin/condominiums'
import { Route as DashboardAnunciosNovoRouteImport } from './routes/dashboard.anuncios.novo'
import { Route as DashboardAnnouncementsNewRouteImport } from './routes/dashboard.announcements.new'
import { Route as PortalProvidersIdRouteImport } from './routes/_portal.providers.$id'
import { Route as PortalAnunciosIdRouteImport } from './routes/_portal.anuncios.$id'
import { Route as PanelProviderAnnouncementsIndexRouteImport } from './routes/panel.provider.announcements.index'
import { Route as PanelDashboardAnnouncementsIndexRouteImport } from './routes/panel.dashboard.announcements.index'
import { Route as PanelProviderAnnouncementsNewRouteImport } from './routes/panel.provider.announcements.new'
import { Route as PanelProviderAnnouncementsIdRouteImport } from './routes/panel.provider.announcements.$id'
import { Route as PanelDashboardAnunciosNovoRouteImport } from './routes/panel.dashboard.anuncios.novo'
import { Route as PanelDashboardAnnouncementsNewRouteImport } from './routes/panel.dashboard.announcements.new'
import { Route as PanelDashboardAnnouncementsIdRouteImport } from './routes/panel.dashboard.announcements.$id'
import { Route as DashboardAnunciosIdPagamentoRouteImport } from './routes/dashboard.anuncios.$id.pagamento'
import { Route as PanelProviderAnunciosIdPagamentoRouteImport } from './routes/panel.provider.anuncios.$id.pagamento'
import { Route as PanelDashboardAnunciosIdPagamentoRouteImport } from './routes/panel.dashboard.anuncios.$id.pagamento'

const PanelRoute = PanelRouteImport.update({
  id: '/panel',
  path: '/panel',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PanelSpectrumRoute = PanelSpectrumRouteImport.update({
  id: '/spectrum',
  path: '/spectrum',
  getParentRoute: () => PanelRoute,
} as any)
const PanelProviderRoute = PanelProviderRouteImport.update({
  id: '/provider',
  path: '/provider',
  getParentRoute: () => PanelRoute,
} as any)
const PanelModerationRoute = PanelModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => PanelRoute,
} as any)
const PanelDashboardRoute = PanelDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAdminRoute = PanelAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PanelRoute,
} as any)
const PanelAccountRoute = PanelAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => PanelRoute,
} as any)
const DashboardCondoSetupRoute = DashboardCondoSetupRouteImport.update({
  id: '/condo-setup',
  path: '/condo-setup',
  getParentRoute: () => DashboardRoute,
} as any)
const PanelProviderIndexRoute = PanelProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelProviderRoute,
} as any)
const PanelModerationIndexRoute = PanelModerationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelModerationRoute,
} as any)
const PanelDashboardIndexRoute = PanelDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PanelDashboardRoute,
} as any)
const PanelProviderConfigurationRoute =
  PanelProviderConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => PanelProviderRoute,
  } as any)
const PanelProviderCondoSetupRoute = PanelProviderCondoSetupRouteImport.update({
  id: '/condo-setup',
  path: '/condo-setup',
  getParentRoute: () => PanelProviderRoute,
} as any)
const PanelProviderAnnouncementsRoute =
  PanelProviderAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => PanelProviderRoute,
  } as any)
const PanelModerationResidentsRoute =
  PanelModerationResidentsRouteImport.update({
    id: '/residents',
    path: '/residents',
    getParentRoute: () => PanelModerationRoute,
  } as any)
const PanelModerationReportsRoute = PanelModerationReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => PanelModerationRoute,
} as any)
const PanelModerationCondominiumRoute =
  PanelModerationCondominiumRouteImport.update({
    id: '/condominium',
    path: '/condominium',
    getParentRoute: () => PanelModerationRoute,
  } as any)
const PanelModerationAnnouncementsRoute =
  PanelModerationAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => PanelModerationRoute,
  } as any)
const PanelDashboardConfigurationRoute =
  PanelDashboardConfigurationRouteImport.update({
    id: '/configuration',
    path: '/configuration',
    getParentRoute: () => PanelDashboardRoute,
  } as any)
const PanelDashboardCondoSetupRoute =
  PanelDashboardCondoSetupRouteImport.update({
    id: '/condo-setup',
    path: '/condo-setup',
    getParentRoute: () => PanelDashboardRoute,
  } as any)
const PanelDashboardAnnouncementsRoute =
  PanelDashboardAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => PanelDashboardRoute,
  } as any)
const PanelAdminUsersRoute = PanelAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => PanelAdminRoute,
} as any)
const PanelAdminProvidersRoute = PanelAdminProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => PanelAdminRoute,
} as any)
const PanelAdminOverviewRoute = PanelAdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => PanelAdminRoute,
} as any)
const PanelAdminCondominiumsRoute = PanelAdminCondominiumsRouteImport.update({
  id: '/condominiums',
  path: '/condominiums',
  getParentRoute: () => PanelAdminRoute,
} as any)
const DashboardAnunciosNovoRoute = DashboardAnunciosNovoRouteImport.update({
  id: '/anuncios/novo',
  path: '/anuncios/novo',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnnouncementsNewRoute =
  DashboardAnnouncementsNewRouteImport.update({
    id: '/announcements/new',
    path: '/announcements/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const PortalProvidersIdRoute = PortalProvidersIdRouteImport.update({
  id: '/providers/$id',
  path: '/providers/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAnunciosIdRoute = PortalAnunciosIdRouteImport.update({
  id: '/anuncios/$id',
  path: '/anuncios/$id',
  getParentRoute: () => PortalRoute,
} as any)
const PanelProviderAnnouncementsIndexRoute =
  PanelProviderAnnouncementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PanelProviderAnnouncementsRoute,
  } as any)
const PanelDashboardAnnouncementsIndexRoute =
  PanelDashboardAnnouncementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => PanelDashboardAnnouncementsRoute,
  } as any)
const PanelProviderAnnouncementsNewRoute =
  PanelProviderAnnouncementsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PanelProviderAnnouncementsRoute,
  } as any)
const PanelProviderAnnouncementsIdRoute =
  PanelProviderAnnouncementsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PanelProviderAnnouncementsRoute,
  } as any)
const PanelDashboardAnunciosNovoRoute =
  PanelDashboardAnunciosNovoRouteImport.update({
    id: '/anuncios/novo',
    path: '/anuncios/novo',
    getParentRoute: () => PanelDashboardRoute,
  } as any)
const PanelDashboardAnnouncementsNewRoute =
  PanelDashboardAnnouncementsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => PanelDashboardAnnouncementsRoute,
  } as any)
const PanelDashboardAnnouncementsIdRoute =
  PanelDashboardAnnouncementsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => PanelDashboardAnnouncementsRoute,
  } as any)
const DashboardAnunciosIdPagamentoRoute =
  DashboardAnunciosIdPagamentoRouteImport.update({
    id: '/anuncios/$id/pagamento',
    path: '/anuncios/$id/pagamento',
    getParentRoute: () => DashboardRoute,
  } as any)
const PanelProviderAnunciosIdPagamentoRoute =
  PanelProviderAnunciosIdPagamentoRouteImport.update({
    id: '/anuncios/$id/pagamento',
    path: '/anuncios/$id/pagamento',
    getParentRoute: () => PanelProviderRoute,
  } as any)
const PanelDashboardAnunciosIdPagamentoRoute =
  PanelDashboardAnunciosIdPagamentoRouteImport.update({
    id: '/anuncios/$id/pagamento',
    path: '/anuncios/$id/pagamento',
    getParentRoute: () => PanelDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PortalIndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/moderation': typeof ModerationRoute
  '/panel': typeof PanelRouteWithChildren
  '/dashboard/condo-setup': typeof DashboardCondoSetupRoute
  '/panel/account': typeof PanelAccountRoute
  '/panel/admin': typeof PanelAdminRouteWithChildren
  '/panel/dashboard': typeof PanelDashboardRouteWithChildren
  '/panel/moderation': typeof PanelModerationRouteWithChildren
  '/panel/provider': typeof PanelProviderRouteWithChildren
  '/panel/spectrum': typeof PanelSpectrumRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/anuncios/$id': typeof PortalAnunciosIdRoute
  '/providers/$id': typeof PortalProvidersIdRoute
  '/dashboard/announcements/new': typeof DashboardAnnouncementsNewRoute
  '/dashboard/anuncios/novo': typeof DashboardAnunciosNovoRoute
  '/panel/admin/condominiums': typeof PanelAdminCondominiumsRoute
  '/panel/admin/overview': typeof PanelAdminOverviewRoute
  '/panel/admin/providers': typeof PanelAdminProvidersRoute
  '/panel/admin/users': typeof PanelAdminUsersRoute
  '/panel/dashboard/announcements': typeof PanelDashboardAnnouncementsRouteWithChildren
  '/panel/dashboard/condo-setup': typeof PanelDashboardCondoSetupRoute
  '/panel/dashboard/configuration': typeof PanelDashboardConfigurationRoute
  '/panel/moderation/announcements': typeof PanelModerationAnnouncementsRoute
  '/panel/moderation/condominium': typeof PanelModerationCondominiumRoute
  '/panel/moderation/reports': typeof PanelModerationReportsRoute
  '/panel/moderation/residents': typeof PanelModerationResidentsRoute
  '/panel/provider/announcements': typeof PanelProviderAnnouncementsRouteWithChildren
  '/panel/provider/condo-setup': typeof PanelProviderCondoSetupRoute
  '/panel/provider/configuration': typeof PanelProviderConfigurationRoute
  '/panel/dashboard/': typeof PanelDashboardIndexRoute
  '/panel/moderation/': typeof PanelModerationIndexRoute
  '/panel/provider/': typeof PanelProviderIndexRoute
  '/dashboard/anuncios/$id/pagamento': typeof DashboardAnunciosIdPagamentoRoute
  '/panel/dashboard/announcements/$id': typeof PanelDashboardAnnouncementsIdRoute
  '/panel/dashboard/announcements/new': typeof PanelDashboardAnnouncementsNewRoute
  '/panel/dashboard/anuncios/novo': typeof PanelDashboardAnunciosNovoRoute
  '/panel/provider/announcements/$id': typeof PanelProviderAnnouncementsIdRoute
  '/panel/provider/announcements/new': typeof PanelProviderAnnouncementsNewRoute
  '/panel/dashboard/announcements/': typeof PanelDashboardAnnouncementsIndexRoute
  '/panel/provider/announcements/': typeof PanelProviderAnnouncementsIndexRoute
  '/panel/dashboard/anuncios/$id/pagamento': typeof PanelDashboardAnunciosIdPagamentoRoute
  '/panel/provider/anuncios/$id/pagamento': typeof PanelProviderAnunciosIdPagamentoRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/moderation': typeof ModerationRoute
  '/panel': typeof PanelRouteWithChildren
  '/dashboard/condo-setup': typeof DashboardCondoSetupRoute
  '/panel/account': typeof PanelAccountRoute
  '/panel/admin': typeof PanelAdminRouteWithChildren
  '/panel/spectrum': typeof PanelSpectrumRoute
  '/': typeof PortalIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/anuncios/$id': typeof PortalAnunciosIdRoute
  '/providers/$id': typeof PortalProvidersIdRoute
  '/dashboard/announcements/new': typeof DashboardAnnouncementsNewRoute
  '/dashboard/anuncios/novo': typeof DashboardAnunciosNovoRoute
  '/panel/admin/condominiums': typeof PanelAdminCondominiumsRoute
  '/panel/admin/overview': typeof PanelAdminOverviewRoute
  '/panel/admin/providers': typeof PanelAdminProvidersRoute
  '/panel/admin/users': typeof PanelAdminUsersRoute
  '/panel/dashboard/condo-setup': typeof PanelDashboardCondoSetupRoute
  '/panel/dashboard/configuration': typeof PanelDashboardConfigurationRoute
  '/panel/moderation/announcements': typeof PanelModerationAnnouncementsRoute
  '/panel/moderation/condominium': typeof PanelModerationCondominiumRoute
  '/panel/moderation/reports': typeof PanelModerationReportsRoute
  '/panel/moderation/residents': typeof PanelModerationResidentsRoute
  '/panel/provider/condo-setup': typeof PanelProviderCondoSetupRoute
  '/panel/provider/configuration': typeof PanelProviderConfigurationRoute
  '/panel/dashboard': typeof PanelDashboardIndexRoute
  '/panel/moderation': typeof PanelModerationIndexRoute
  '/panel/provider': typeof PanelProviderIndexRoute
  '/dashboard/anuncios/$id/pagamento': typeof DashboardAnunciosIdPagamentoRoute
  '/panel/dashboard/announcements/$id': typeof PanelDashboardAnnouncementsIdRoute
  '/panel/dashboard/announcements/new': typeof PanelDashboardAnnouncementsNewRoute
  '/panel/dashboard/anuncios/novo': typeof PanelDashboardAnunciosNovoRoute
  '/panel/provider/announcements/$id': typeof PanelProviderAnnouncementsIdRoute
  '/panel/provider/announcements/new': typeof PanelProviderAnnouncementsNewRoute
  '/panel/dashboard/announcements': typeof PanelDashboardAnnouncementsIndexRoute
  '/panel/provider/announcements': typeof PanelProviderAnnouncementsIndexRoute
  '/panel/dashboard/anuncios/$id/pagamento': typeof PanelDashboardAnunciosIdPagamentoRoute
  '/panel/provider/anuncios/$id/pagamento': typeof PanelProviderAnunciosIdPagamentoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_portal': typeof PortalRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/moderation': typeof ModerationRoute
  '/panel': typeof PanelRouteWithChildren
  '/dashboard/condo-setup': typeof DashboardCondoSetupRoute
  '/panel/account': typeof PanelAccountRoute
  '/panel/admin': typeof PanelAdminRouteWithChildren
  '/panel/dashboard': typeof PanelDashboardRouteWithChildren
  '/panel/moderation': typeof PanelModerationRouteWithChildren
  '/panel/provider': typeof PanelProviderRouteWithChildren
  '/panel/spectrum': typeof PanelSpectrumRoute
  '/_portal/': typeof PortalIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_portal/anuncios/$id': typeof PortalAnunciosIdRoute
  '/_portal/providers/$id': typeof PortalProvidersIdRoute
  '/dashboard/announcements/new': typeof DashboardAnnouncementsNewRoute
  '/dashboard/anuncios/novo': typeof DashboardAnunciosNovoRoute
  '/panel/admin/condominiums': typeof PanelAdminCondominiumsRoute
  '/panel/admin/overview': typeof PanelAdminOverviewRoute
  '/panel/admin/providers': typeof PanelAdminProvidersRoute
  '/panel/admin/users': typeof PanelAdminUsersRoute
  '/panel/dashboard/announcements': typeof PanelDashboardAnnouncementsRouteWithChildren
  '/panel/dashboard/condo-setup': typeof PanelDashboardCondoSetupRoute
  '/panel/dashboard/configuration': typeof PanelDashboardConfigurationRoute
  '/panel/moderation/announcements': typeof PanelModerationAnnouncementsRoute
  '/panel/moderation/condominium': typeof PanelModerationCondominiumRoute
  '/panel/moderation/reports': typeof PanelModerationReportsRoute
  '/panel/moderation/residents': typeof PanelModerationResidentsRoute
  '/panel/provider/announcements': typeof PanelProviderAnnouncementsRouteWithChildren
  '/panel/provider/condo-setup': typeof PanelProviderCondoSetupRoute
  '/panel/provider/configuration': typeof PanelProviderConfigurationRoute
  '/panel/dashboard/': typeof PanelDashboardIndexRoute
  '/panel/moderation/': typeof PanelModerationIndexRoute
  '/panel/provider/': typeof PanelProviderIndexRoute
  '/dashboard/anuncios/$id/pagamento': typeof DashboardAnunciosIdPagamentoRoute
  '/panel/dashboard/announcements/$id': typeof PanelDashboardAnnouncementsIdRoute
  '/panel/dashboard/announcements/new': typeof PanelDashboardAnnouncementsNewRoute
  '/panel/dashboard/anuncios/novo': typeof PanelDashboardAnunciosNovoRoute
  '/panel/provider/announcements/$id': typeof PanelProviderAnnouncementsIdRoute
  '/panel/provider/announcements/new': typeof PanelProviderAnnouncementsNewRoute
  '/panel/dashboard/announcements/': typeof PanelDashboardAnnouncementsIndexRoute
  '/panel/provider/announcements/': typeof PanelProviderAnnouncementsIndexRoute
  '/panel/dashboard/anuncios/$id/pagamento': typeof PanelDashboardAnunciosIdPagamentoRoute
  '/panel/provider/anuncios/$id/pagamento': typeof PanelProviderAnunciosIdPagamentoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/moderation'
    | '/panel'
    | '/dashboard/condo-setup'
    | '/panel/account'
    | '/panel/admin'
    | '/panel/dashboard'
    | '/panel/moderation'
    | '/panel/provider'
    | '/panel/spectrum'
    | '/dashboard/'
    | '/anuncios/$id'
    | '/providers/$id'
    | '/dashboard/announcements/new'
    | '/dashboard/anuncios/novo'
    | '/panel/admin/condominiums'
    | '/panel/admin/overview'
    | '/panel/admin/providers'
    | '/panel/admin/users'
    | '/panel/dashboard/announcements'
    | '/panel/dashboard/condo-setup'
    | '/panel/dashboard/configuration'
    | '/panel/moderation/announcements'
    | '/panel/moderation/condominium'
    | '/panel/moderation/reports'
    | '/panel/moderation/residents'
    | '/panel/provider/announcements'
    | '/panel/provider/condo-setup'
    | '/panel/provider/configuration'
    | '/panel/dashboard/'
    | '/panel/moderation/'
    | '/panel/provider/'
    | '/dashboard/anuncios/$id/pagamento'
    | '/panel/dashboard/announcements/$id'
    | '/panel/dashboard/announcements/new'
    | '/panel/dashboard/anuncios/novo'
    | '/panel/provider/announcements/$id'
    | '/panel/provider/announcements/new'
    | '/panel/dashboard/announcements/'
    | '/panel/provider/announcements/'
    | '/panel/dashboard/anuncios/$id/pagamento'
    | '/panel/provider/anuncios/$id/pagamento'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/auth'
    | '/moderation'
    | '/panel'
    | '/dashboard/condo-setup'
    | '/panel/account'
    | '/panel/admin'
    | '/panel/spectrum'
    | '/'
    | '/dashboard'
    | '/anuncios/$id'
    | '/providers/$id'
    | '/dashboard/announcements/new'
    | '/dashboard/anuncios/novo'
    | '/panel/admin/condominiums'
    | '/panel/admin/overview'
    | '/panel/admin/providers'
    | '/panel/admin/users'
    | '/panel/dashboard/condo-setup'
    | '/panel/dashboard/configuration'
    | '/panel/moderation/announcements'
    | '/panel/moderation/condominium'
    | '/panel/moderation/reports'
    | '/panel/moderation/residents'
    | '/panel/provider/condo-setup'
    | '/panel/provider/configuration'
    | '/panel/dashboard'
    | '/panel/moderation'
    | '/panel/provider'
    | '/dashboard/anuncios/$id/pagamento'
    | '/panel/dashboard/announcements/$id'
    | '/panel/dashboard/announcements/new'
    | '/panel/dashboard/anuncios/novo'
    | '/panel/provider/announcements/$id'
    | '/panel/provider/announcements/new'
    | '/panel/dashboard/announcements'
    | '/panel/provider/announcements'
    | '/panel/dashboard/anuncios/$id/pagamento'
    | '/panel/provider/anuncios/$id/pagamento'
  id:
    | '__root__'
    | '/_portal'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/moderation'
    | '/panel'
    | '/dashboard/condo-setup'
    | '/panel/account'
    | '/panel/admin'
    | '/panel/dashboard'
    | '/panel/moderation'
    | '/panel/provider'
    | '/panel/spectrum'
    | '/_portal/'
    | '/dashboard/'
    | '/_portal/anuncios/$id'
    | '/_portal/providers/$id'
    | '/dashboard/announcements/new'
    | '/dashboard/anuncios/novo'
    | '/panel/admin/condominiums'
    | '/panel/admin/overview'
    | '/panel/admin/providers'
    | '/panel/admin/users'
    | '/panel/dashboard/announcements'
    | '/panel/dashboard/condo-setup'
    | '/panel/dashboard/configuration'
    | '/panel/moderation/announcements'
    | '/panel/moderation/condominium'
    | '/panel/moderation/reports'
    | '/panel/moderation/residents'
    | '/panel/provider/announcements'
    | '/panel/provider/condo-setup'
    | '/panel/provider/configuration'
    | '/panel/dashboard/'
    | '/panel/moderation/'
    | '/panel/provider/'
    | '/dashboard/anuncios/$id/pagamento'
    | '/panel/dashboard/announcements/$id'
    | '/panel/dashboard/announcements/new'
    | '/panel/dashboard/anuncios/novo'
    | '/panel/provider/announcements/$id'
    | '/panel/provider/announcements/new'
    | '/panel/dashboard/announcements/'
    | '/panel/provider/announcements/'
    | '/panel/dashboard/anuncios/$id/pagamento'
    | '/panel/provider/anuncios/$id/pagamento'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PortalRoute: typeof PortalRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ModerationRoute: typeof ModerationRoute
  PanelRoute: typeof PanelRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/panel': {
      id: '/panel'
      path: '/panel'
      fullPath: '/panel'
      preLoaderRoute: typeof PanelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_portal/': {
      id: '/_portal/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/panel/spectrum': {
      id: '/panel/spectrum'
      path: '/spectrum'
      fullPath: '/panel/spectrum'
      preLoaderRoute: typeof PanelSpectrumRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/provider': {
      id: '/panel/provider'
      path: '/provider'
      fullPath: '/panel/provider'
      preLoaderRoute: typeof PanelProviderRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/moderation': {
      id: '/panel/moderation'
      path: '/moderation'
      fullPath: '/panel/moderation'
      preLoaderRoute: typeof PanelModerationRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/dashboard': {
      id: '/panel/dashboard'
      path: '/dashboard'
      fullPath: '/panel/dashboard'
      preLoaderRoute: typeof PanelDashboardRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/admin': {
      id: '/panel/admin'
      path: '/admin'
      fullPath: '/panel/admin'
      preLoaderRoute: typeof PanelAdminRouteImport
      parentRoute: typeof PanelRoute
    }
    '/panel/account': {
      id: '/panel/account'
      path: '/account'
      fullPath: '/panel/account'
      preLoaderRoute: typeof PanelAccountRouteImport
      parentRoute: typeof PanelRoute
    }
    '/dashboard/condo-setup': {
      id: '/dashboard/condo-setup'
      path: '/condo-setup'
      fullPath: '/dashboard/condo-setup'
      preLoaderRoute: typeof DashboardCondoSetupRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/panel/provider/': {
      id: '/panel/provider/'
      path: '/'
      fullPath: '/panel/provider/'
      preLoaderRoute: typeof PanelProviderIndexRouteImport
      parentRoute: typeof PanelProviderRoute
    }
    '/panel/moderation/': {
      id: '/panel/moderation/'
      path: '/'
      fullPath: '/panel/moderation/'
      preLoaderRoute: typeof PanelModerationIndexRouteImport
      parentRoute: typeof PanelModerationRoute
    }
    '/panel/dashboard/': {
      id: '/panel/dashboard/'
      path: '/'
      fullPath: '/panel/dashboard/'
      preLoaderRoute: typeof PanelDashboardIndexRouteImport
      parentRoute: typeof PanelDashboardRoute
    }
    '/panel/provider/configuration': {
      id: '/panel/provider/configuration'
      path: '/configuration'
      fullPath: '/panel/provider/configuration'
      preLoaderRoute: typeof PanelProviderConfigurationRouteImport
      parentRoute: typeof PanelProviderRoute
    }
    '/panel/provider/condo-setup': {
      id: '/panel/provider/condo-setup'
      path: '/condo-setup'
      fullPath: '/panel/provider/condo-setup'
      preLoaderRoute: typeof PanelProviderCondoSetupRouteImport
      parentRoute: typeof PanelProviderRoute
    }
    '/panel/provider/announcements': {
      id: '/panel/provider/announcements'
      path: '/announcements'
      fullPath: '/panel/provider/announcements'
      preLoaderRoute: typeof PanelProviderAnnouncementsRouteImport
      parentRoute: typeof PanelProviderRoute
    }
    '/panel/moderation/residents': {
      id: '/panel/moderation/residents'
      path: '/residents'
      fullPath: '/panel/moderation/residents'
      preLoaderRoute: typeof PanelModerationResidentsRouteImport
      parentRoute: typeof PanelModerationRoute
    }
    '/panel/moderation/reports': {
      id: '/panel/moderation/reports'
      path: '/reports'
      fullPath: '/panel/moderation/reports'
      preLoaderRoute: typeof PanelModerationReportsRouteImport
      parentRoute: typeof PanelModerationRoute
    }
    '/panel/moderation/condominium': {
      id: '/panel/moderation/condominium'
      path: '/condominium'
      fullPath: '/panel/moderation/condominium'
      preLoaderRoute: typeof PanelModerationCondominiumRouteImport
      parentRoute: typeof PanelModerationRoute
    }
    '/panel/moderation/announcements': {
      id: '/panel/moderation/announcements'
      path: '/announcements'
      fullPath: '/panel/moderation/announcements'
      preLoaderRoute: typeof PanelModerationAnnouncementsRouteImport
      parentRoute: typeof PanelModerationRoute
    }
    '/panel/dashboard/configuration': {
      id: '/panel/dashboard/configuration'
      path: '/configuration'
      fullPath: '/panel/dashboard/configuration'
      preLoaderRoute: typeof PanelDashboardConfigurationRouteImport
      parentRoute: typeof PanelDashboardRoute
    }
    '/panel/dashboard/condo-setup': {
      id: '/panel/dashboard/condo-setup'
      path: '/condo-setup'
      fullPath: '/panel/dashboard/condo-setup'
      preLoaderRoute: typeof PanelDashboardCondoSetupRouteImport
      parentRoute: typeof PanelDashboardRoute
    }
    '/panel/dashboard/announcements': {
      id: '/panel/dashboard/announcements'
      path: '/announcements'
      fullPath: '/panel/dashboard/announcements'
      preLoaderRoute: typeof PanelDashboardAnnouncementsRouteImport
      parentRoute: typeof PanelDashboardRoute
    }
    '/panel/admin/users': {
      id: '/panel/admin/users'
      path: '/users'
      fullPath: '/panel/admin/users'
      preLoaderRoute: typeof PanelAdminUsersRouteImport
      parentRoute: typeof PanelAdminRoute
    }
    '/panel/admin/providers': {
      id: '/panel/admin/providers'
      path: '/providers'
      fullPath: '/panel/admin/providers'
      preLoaderRoute: typeof PanelAdminProvidersRouteImport
      parentRoute: typeof PanelAdminRoute
    }
    '/panel/admin/overview': {
      id: '/panel/admin/overview'
      path: '/overview'
      fullPath: '/panel/admin/overview'
      preLoaderRoute: typeof PanelAdminOverviewRouteImport
      parentRoute: typeof PanelAdminRoute
    }
    '/panel/admin/condominiums': {
      id: '/panel/admin/condominiums'
      path: '/condominiums'
      fullPath: '/panel/admin/condominiums'
      preLoaderRoute: typeof PanelAdminCondominiumsRouteImport
      parentRoute: typeof PanelAdminRoute
    }
    '/dashboard/anuncios/novo': {
      id: '/dashboard/anuncios/novo'
      path: '/anuncios/novo'
      fullPath: '/dashboard/anuncios/novo'
      preLoaderRoute: typeof DashboardAnunciosNovoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/announcements/new': {
      id: '/dashboard/announcements/new'
      path: '/announcements/new'
      fullPath: '/dashboard/announcements/new'
      preLoaderRoute: typeof DashboardAnnouncementsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_portal/providers/$id': {
      id: '/_portal/providers/$id'
      path: '/providers/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof PortalProvidersIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/anuncios/$id': {
      id: '/_portal/anuncios/$id'
      path: '/anuncios/$id'
      fullPath: '/anuncios/$id'
      preLoaderRoute: typeof PortalAnunciosIdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/panel/provider/announcements/': {
      id: '/panel/provider/announcements/'
      path: '/'
      fullPath: '/panel/provider/announcements/'
      preLoaderRoute: typeof PanelProviderAnnouncementsIndexRouteImport
      parentRoute: typeof PanelProviderAnnouncementsRoute
    }
    '/panel/dashboard/announcements/': {
      id: '/panel/dashboard/announcements/'
      path: '/'
      fullPath: '/panel/dashboard/announcements/'
      preLoaderRoute: typeof PanelDashboardAnnouncementsIndexRouteImport
      parentRoute: typeof PanelDashboardAnnouncementsRoute
    }
    '/panel/provider/announcements/new': {
      id: '/panel/provider/announcements/new'
      path: '/new'
      fullPath: '/panel/provider/announcements/new'
      preLoaderRoute: typeof PanelProviderAnnouncementsNewRouteImport
      parentRoute: typeof PanelProviderAnnouncementsRoute
    }
    '/panel/provider/announcements/$id': {
      id: '/panel/provider/announcements/$id'
      path: '/$id'
      fullPath: '/panel/provider/announcements/$id'
      preLoaderRoute: typeof PanelProviderAnnouncementsIdRouteImport
      parentRoute: typeof PanelProviderAnnouncementsRoute
    }
    '/panel/dashboard/anuncios/novo': {
      id: '/panel/dashboard/anuncios/novo'
      path: '/anuncios/novo'
      fullPath: '/panel/dashboard/anuncios/novo'
      preLoaderRoute: typeof PanelDashboardAnunciosNovoRouteImport
      parentRoute: typeof PanelDashboardRoute
    }
    '/panel/dashboard/announcements/new': {
      id: '/panel/dashboard/announcements/new'
      path: '/new'
      fullPath: '/panel/dashboard/announcements/new'
      preLoaderRoute: typeof PanelDashboardAnnouncementsNewRouteImport
      parentRoute: typeof PanelDashboardAnnouncementsRoute
    }
    '/panel/dashboard/announcements/$id': {
      id: '/panel/dashboard/announcements/$id'
      path: '/$id'
      fullPath: '/panel/dashboard/announcements/$id'
      preLoaderRoute: typeof PanelDashboardAnnouncementsIdRouteImport
      parentRoute: typeof PanelDashboardAnnouncementsRoute
    }
    '/dashboard/anuncios/$id/pagamento': {
      id: '/dashboard/anuncios/$id/pagamento'
      path: '/anuncios/$id/pagamento'
      fullPath: '/dashboard/anuncios/$id/pagamento'
      preLoaderRoute: typeof DashboardAnunciosIdPagamentoRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/panel/provider/anuncios/$id/pagamento': {
      id: '/panel/provider/anuncios/$id/pagamento'
      path: '/anuncios/$id/pagamento'
      fullPath: '/panel/provider/anuncios/$id/pagamento'
      preLoaderRoute: typeof PanelProviderAnunciosIdPagamentoRouteImport
      parentRoute: typeof PanelProviderRoute
    }
    '/panel/dashboard/anuncios/$id/pagamento': {
      id: '/panel/dashboard/anuncios/$id/pagamento'
      path: '/anuncios/$id/pagamento'
      fullPath: '/panel/dashboard/anuncios/$id/pagamento'
      preLoaderRoute: typeof PanelDashboardAnunciosIdPagamentoRouteImport
      parentRoute: typeof PanelDashboardRoute
    }
  }
}

interface PortalRouteChildren {
  PortalIndexRoute: typeof PortalIndexRoute
  PortalAnunciosIdRoute: typeof PortalAnunciosIdRoute
  PortalProvidersIdRoute: typeof PortalProvidersIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalIndexRoute: PortalIndexRoute,
  PortalAnunciosIdRoute: PortalAnunciosIdRoute,
  PortalProvidersIdRoute: PortalProvidersIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface DashboardRouteChildren {
  DashboardCondoSetupRoute: typeof DashboardCondoSetupRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardAnnouncementsNewRoute: typeof DashboardAnnouncementsNewRoute
  DashboardAnunciosNovoRoute: typeof DashboardAnunciosNovoRoute
  DashboardAnunciosIdPagamentoRoute: typeof DashboardAnunciosIdPagamentoRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCondoSetupRoute: DashboardCondoSetupRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardAnnouncementsNewRoute: DashboardAnnouncementsNewRoute,
  DashboardAnunciosNovoRoute: DashboardAnunciosNovoRoute,
  DashboardAnunciosIdPagamentoRoute: DashboardAnunciosIdPagamentoRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface PanelAdminRouteChildren {
  PanelAdminCondominiumsRoute: typeof PanelAdminCondominiumsRoute
  PanelAdminOverviewRoute: typeof PanelAdminOverviewRoute
  PanelAdminProvidersRoute: typeof PanelAdminProvidersRoute
  PanelAdminUsersRoute: typeof PanelAdminUsersRoute
}

const PanelAdminRouteChildren: PanelAdminRouteChildren = {
  PanelAdminCondominiumsRoute: PanelAdminCondominiumsRoute,
  PanelAdminOverviewRoute: PanelAdminOverviewRoute,
  PanelAdminProvidersRoute: PanelAdminProvidersRoute,
  PanelAdminUsersRoute: PanelAdminUsersRoute,
}

const PanelAdminRouteWithChildren = PanelAdminRoute._addFileChildren(
  PanelAdminRouteChildren,
)

interface PanelDashboardAnnouncementsRouteChildren {
  PanelDashboardAnnouncementsIdRoute: typeof PanelDashboardAnnouncementsIdRoute
  PanelDashboardAnnouncementsNewRoute: typeof PanelDashboardAnnouncementsNewRoute
  PanelDashboardAnnouncementsIndexRoute: typeof PanelDashboardAnnouncementsIndexRoute
}

const PanelDashboardAnnouncementsRouteChildren: PanelDashboardAnnouncementsRouteChildren =
  {
    PanelDashboardAnnouncementsIdRoute: PanelDashboardAnnouncementsIdRoute,
    PanelDashboardAnnouncementsNewRoute: PanelDashboardAnnouncementsNewRoute,
    PanelDashboardAnnouncementsIndexRoute:
      PanelDashboardAnnouncementsIndexRoute,
  }

const PanelDashboardAnnouncementsRouteWithChildren =
  PanelDashboardAnnouncementsRoute._addFileChildren(
    PanelDashboardAnnouncementsRouteChildren,
  )

interface PanelDashboardRouteChildren {
  PanelDashboardAnnouncementsRoute: typeof PanelDashboardAnnouncementsRouteWithChildren
  PanelDashboardCondoSetupRoute: typeof PanelDashboardCondoSetupRoute
  PanelDashboardConfigurationRoute: typeof PanelDashboardConfigurationRoute
  PanelDashboardIndexRoute: typeof PanelDashboardIndexRoute
  PanelDashboardAnunciosNovoRoute: typeof PanelDashboardAnunciosNovoRoute
  PanelDashboardAnunciosIdPagamentoRoute: typeof PanelDashboardAnunciosIdPagamentoRoute
}

const PanelDashboardRouteChildren: PanelDashboardRouteChildren = {
  PanelDashboardAnnouncementsRoute:
    PanelDashboardAnnouncementsRouteWithChildren,
  PanelDashboardCondoSetupRoute: PanelDashboardCondoSetupRoute,
  PanelDashboardConfigurationRoute: PanelDashboardConfigurationRoute,
  PanelDashboardIndexRoute: PanelDashboardIndexRoute,
  PanelDashboardAnunciosNovoRoute: PanelDashboardAnunciosNovoRoute,
  PanelDashboardAnunciosIdPagamentoRoute:
    PanelDashboardAnunciosIdPagamentoRoute,
}

const PanelDashboardRouteWithChildren = PanelDashboardRoute._addFileChildren(
  PanelDashboardRouteChildren,
)

interface PanelModerationRouteChildren {
  PanelModerationAnnouncementsRoute: typeof PanelModerationAnnouncementsRoute
  PanelModerationCondominiumRoute: typeof PanelModerationCondominiumRoute
  PanelModerationReportsRoute: typeof PanelModerationReportsRoute
  PanelModerationResidentsRoute: typeof PanelModerationResidentsRoute
  PanelModerationIndexRoute: typeof PanelModerationIndexRoute
}

const PanelModerationRouteChildren: PanelModerationRouteChildren = {
  PanelModerationAnnouncementsRoute: PanelModerationAnnouncementsRoute,
  PanelModerationCondominiumRoute: PanelModerationCondominiumRoute,
  PanelModerationReportsRoute: PanelModerationReportsRoute,
  PanelModerationResidentsRoute: PanelModerationResidentsRoute,
  PanelModerationIndexRoute: PanelModerationIndexRoute,
}

const PanelModerationRouteWithChildren = PanelModerationRoute._addFileChildren(
  PanelModerationRouteChildren,
)

interface PanelProviderAnnouncementsRouteChildren {
  PanelProviderAnnouncementsIdRoute: typeof PanelProviderAnnouncementsIdRoute
  PanelProviderAnnouncementsNewRoute: typeof PanelProviderAnnouncementsNewRoute
  PanelProviderAnnouncementsIndexRoute: typeof PanelProviderAnnouncementsIndexRoute
}

const PanelProviderAnnouncementsRouteChildren: PanelProviderAnnouncementsRouteChildren =
  {
    PanelProviderAnnouncementsIdRoute: PanelProviderAnnouncementsIdRoute,
    PanelProviderAnnouncementsNewRoute: PanelProviderAnnouncementsNewRoute,
    PanelProviderAnnouncementsIndexRoute: PanelProviderAnnouncementsIndexRoute,
  }

const PanelProviderAnnouncementsRouteWithChildren =
  PanelProviderAnnouncementsRoute._addFileChildren(
    PanelProviderAnnouncementsRouteChildren,
  )

interface PanelProviderRouteChildren {
  PanelProviderAnnouncementsRoute: typeof PanelProviderAnnouncementsRouteWithChildren
  PanelProviderCondoSetupRoute: typeof PanelProviderCondoSetupRoute
  PanelProviderConfigurationRoute: typeof PanelProviderConfigurationRoute
  PanelProviderIndexRoute: typeof PanelProviderIndexRoute
  PanelProviderAnunciosIdPagamentoRoute: typeof PanelProviderAnunciosIdPagamentoRoute
}

const PanelProviderRouteChildren: PanelProviderRouteChildren = {
  PanelProviderAnnouncementsRoute: PanelProviderAnnouncementsRouteWithChildren,
  PanelProviderCondoSetupRoute: PanelProviderCondoSetupRoute,
  PanelProviderConfigurationRoute: PanelProviderConfigurationRoute,
  PanelProviderIndexRoute: PanelProviderIndexRoute,
  PanelProviderAnunciosIdPagamentoRoute: PanelProviderAnunciosIdPagamentoRoute,
}

const PanelProviderRouteWithChildren = PanelProviderRoute._addFileChildren(
  PanelProviderRouteChildren,
)

interface PanelRouteChildren {
  PanelAccountRoute: typeof PanelAccountRoute
  PanelAdminRoute: typeof PanelAdminRouteWithChildren
  PanelDashboardRoute: typeof PanelDashboardRouteWithChildren
  PanelModerationRoute: typeof PanelModerationRouteWithChildren
  PanelProviderRoute: typeof PanelProviderRouteWithChildren
  PanelSpectrumRoute: typeof PanelSpectrumRoute
}

const PanelRouteChildren: PanelRouteChildren = {
  PanelAccountRoute: PanelAccountRoute,
  PanelAdminRoute: PanelAdminRouteWithChildren,
  PanelDashboardRoute: PanelDashboardRouteWithChildren,
  PanelModerationRoute: PanelModerationRouteWithChildren,
  PanelProviderRoute: PanelProviderRouteWithChildren,
  PanelSpectrumRoute: PanelSpectrumRoute,
}

const PanelRouteWithChildren = PanelRoute._addFileChildren(PanelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PortalRoute: PortalRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ModerationRoute: ModerationRoute,
  PanelRoute: PanelRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
